config/routes.rb
Rails.application.routes.draw do
  resources :ransack_saved_searches

  namespace :ransack_advanced_plus do
    get 'form_builder/:model', to: 'form_builder#index', as: 'form_builder'
    get 'operators/:model/:attribute', to: 'form_builder#operators', as: 'operators'
    get 'values/:model/:attribute/:operator', to: 'form_builder#values', as: 'values'
  end

end

app/models/ransack_saved_search.rb
class RansackSavedSearch < ActiveRecord::Base
  validates_presence_of :context, :description, :search_params

  serialize :search_params
end

app/controllers/concerns/ransack_advanced_plus/saved_search_utils.rb
module RansackAdvancedPlus
  module SavedSearchUtils
    extend ActiveSupport::Concern

    # Perform saved searches actions to provide full functionality with one method
    def perform_saved_searches_actions(context, params={})
      get_saved_searches(context)
      save_or_update_saved_search(params.merge(context: context))
      get_params_to_search(context)
    end

    # Get list of Saved Search by context
    def get_saved_searches(context)
      @saved_searches = RansackSavedSearch.where(context: context)
    end

    # Return params of Saved Search or search form params
    def get_params_to_search(context)
      if params[:saved_search].present?
        @saved_search = RansackSavedSearch.find_by(id: params[:saved_search], context: context)
      end
      return params[:q] if params[:use_search_params].present?
      params[:q] = @saved_search.try(:search_params) || params[:q]
    end

    # Save or update Saved Search
    def save_or_update_saved_search(params)
      if params[:save_new_search].present? || params[:save_search].present?
        if params[:save_new_search].present?
          @saved_search = new_saved_search(params)
        elsif params[:save_search].present? && params[:saved_search].present?
          @saved_search = update_saved_search(params)
        elsif params[:save_search].present?
          @saved_search = new_saved_search(params)
        end

        if @saved_search.save
          flash[:notice] = t('ransack.saved_search.save.success')
        else
          flash[:error] = t('ransack.saved_search.save.error')
        end
      end
    end

    def new_saved_search(params)
      RansackSavedSearch.new(
       context: params[:context], description: params[:description],
       search_params: params[:q]
      )
    end

    def update_saved_search(params)
      saved_search = RansackSavedSearch.find_by(id: params[:saved_search], context: params[:context])
      saved_search.description = params[:description]
      saved_search.search_params = params[:q]
      saved_search
    end
  end
end

app/controllers/ransack_advanced_plus/application_controller.rb
module RansackAdvancedPlus
  class ApplicationController < ::ApplicationController

  end
end

app/controllers/ransack_advanced_plus/form_builder_controller.rb
module RansackAdvancedPlus
  class FormBuilderController < ApplicationController

    def index
      rap_service = RansackAdvancedPlus::Service.new(params[:model])
      rap_service.build_form_context(view_context)
      type = params[:type] || 'grouping'
      builder = rap_service.builder_by_type(type, params[:group_index], params[:condition_index])
      html = nil
      builder.send("#{type}_fields", builder.object.send("build_#{type}"), child_index: DateTime.now.strftime('%s')) do |ff|
        @rap_model_name = params[:model]
        @rap_associations_names = params[:associations_models].present? ? params[:associations_models].split(',') : rap_service.klass.ransackable_associations
        @rap_operators = {default: 'eq'}
        locals_params = {frm: ff}
        locals_params.merge!({frm_condition: builder}) if type=='value'
        html = render_to_string(partial: 'ransack_advanced_plus/' + type.to_s + "_fields", locals: locals_params)
      end
      render html: html
    end

    def operators
      rap_service = RansackAdvancedPlus::Service.new(params[:model])
      rap_service.build_form_context(view_context)
      operators = rap_service.attribute_operators(params[:attribute])
      @rap_operators = {only: operators}
      @f = rap_service.builder_condition
      render html: render_to_string(partial: 'ransack_advanced_plus/predicates', locals: {frm: @f})
    end

    def values
      rap_service = RansackAdvancedPlus::Service.new(params[:model])
      rap_service.build_form_context(view_context)
      @rap_operador = params[:operator]
      builder = rap_service.builder_condition(params[:group_index], params[:condition_index])
      values = params[:values].present? ? params[:values].split(',') : ['']
      @attribute_type = params[:type].present? ? params[:type] : rap_service.attribute_type(params[:attribute])
      html = []
      values.each do |v|
        builder.value_fields(builder.object.build_value(v), child_index: DateTime.now.strftime('%s')) do |ff|
          html << render_to_string(partial: 'ransack_advanced_plus/value_fields', locals: {frm: ff, frm_condition: builder, current_value: v})
        end
      end
      render html: html.join.html_safe
    end

  end
end

app/controllers/ransack_advanced_plus/saved_searches_controller.rb
module RansackAdvancedPlus
  class SavedSearchesController < ApplicationController
    before_action :set_saved_search, only: [:destroy]

    # DELETE /saved_search/1
    # DELETE /saved_search/1.json
    def destroy
      @saved_search.destroy
      respond_to do |format|
        redirect_path = params[:redirect_to] || root_path
        format.html { redirect_to redirect_path, notice: t('ransack.saved_search.delete.success') }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_saved_search
        @saved_search = RansackSavedSearch.find(params[:id])
      end
  end
end

app/helpers/ransack_advanced_plus_helper.rb
module RansackAdvancedPlusHelper

  def ransack_advanced_plus_form(object, url, *args)
    arguments = args.inject(:merge)
    @ransack_object = object
    @ransack_object.build_grouping unless @ransack_object.groupings.any?
    @rap_model_name = @ransack_object.context.klass.name.tableize.singularize
    rap_service = RansackAdvancedPlus::Service.new(@rap_model_name)
    if arguments.present?
      associations = arguments[:associations]
    else
      associations = nil
    end
    @rap_operators = {default: :eq}
    @rap_associations = rap_service.build_associations(associations)
    @rap_associations_names = @rap_associations.keys
    render partial: 'ransack_advanced_plus/advanced_search', locals: {search_url: url, redirect_path: url}
  end

end

app/views/ransack_advanced_plus/_advanced_search.html.erb
<div class="ransack-advanced-search">

  <div class="row">
    <div class="col-md-12">
      <%= search_form_for(@ransack_object, url: search_url, html: { method: :post, class: 'form-inline ransack-form', role: 'form', data: {rap_model: @rap_model_name}}) do |frm| %>
        <script>
          document.rap_associations_dictionary = <%= @rap_associations.to_json.html_safe %>
        </script>

        <% if @saved_search %>
          <div class="form-group">
            <%= label_tag 'Descrição da Busca (necessária para salvar a busca)' %>
            <%= text_field_tag :description, @saved_search.try(:description), class: 'form-control input-sm' %>

            <%= hidden_field_tag :saved_search, @saved_search.id %>
            <%= hidden_field_tag :use_search_params, true %>
          </div>
          <% end %>

        <h4><%= t('ransack.advanced_search.condition_group.title') %></h4>
        <div class="form-group">
          <%= frm.grouping_fields do |g| %>
              <%= render partial: 'ransack_advanced_plus/grouping_fields', locals: {frm: g} %>
          <% end %>
          <a href="" data-rap-type="grouping" class="ransack_advanced_plus_add_button">Grupo</a>
        </div>

        <!-- <%= label_tag :distinct, 'Return distinct records?' %> -->
        <!-- <%= check_box_tag :distinct, '1', params[:distinct].to_i == 1 %> -->
        <div class="clearfix"></div>
        <div class="ransack-action-buttons">
          <%= frm.submit t('ransack.advanced_search.form.submit_text'), class: 'btn btn-primary' %>
          <%= frm.submit t('ransack.advanced_search.form.save_submit_text'), name: 'save_search', class: 'btn btn-primary' %>
          <%= frm.submit t('ransack.advanced_search.form.save_new_submit_text'), name: 'save_new_search', class: 'btn btn-primary' %>
          <%= link_to t('ransack.advanced_search.form.clear_search_text'), redirect_path, class: 'btn btn-default' %>
        </div>
      <% end %>

      <fieldset>
        <legend>DEBUG</legend>
        <%= @ransack_object.result.to_sql %>
      </fieldset>
    </div>
  </div>
</div>

app/views/ransack_advanced_plus/_attribute_fields.html.erb
<span class="fields" data-object-name="<%= frm.object_name %>">
  <%= frm.attribute_select({associations: @rap_associations_names}, {class: 'ransack-attribute-select form-control input-sm'}) %>
</span>

app/views/ransack_advanced_plus/_condition_fields.html.erb
<% group_index = frm.object_name.scan(/\d+/).first %>
<% condition_index = frm.object_name.scan(/\d+/).last %>
<% rap_service = RansackAdvancedPlus::Service.new(@rap_model_name) %>
<div class="fields condition ransack-condition-fields" data-object-name="<%= frm.object_name %>" data-rap-group-index="<%= group_index %>" data-rap-condition-index="<%= condition_index %>">
  <%= render 'ransack_advanced_plus/remove_button' %>

  <span class="ransack-attribute-fields">
    <%= frm.attribute_fields do |a| %>
      <% @rap_operators = {only: rap_service.attribute_operators(a.object.name)} %>
      <% @attribute_type = rap_service.attribute_type(a.object.name) %>
      <%= render partial: 'ransack_advanced_plus/attribute_fields', locals: {frm: a} %>
    <% end %>
  </span>

  <span class="ransack-predicate-fields">
    <%= render partial: 'ransack_advanced_plus/predicates', locals: {frm: frm} %>
  </span>

  <span class="ransack-value-fields">
    <span class="fields_content">
      <%= frm.value_fields do |v| %>
        <%= render partial: 'ransack_advanced_plus/value_fields', locals: {frm: v, frm_condition: frm} %>
      <% end %>
    </span>
    <a href="" data-rap-type="value" class="ransack_advanced_plus_add_button">Valor</a>
  </span>

</div>

app/views/ransack_advanced_plus/_grouping_fields.html.erb
<% group_index = frm.object_name.scan(/\d+/).first %>
<div class="fields ransack-grouping-fields" data-object-name="<%= frm.object_name %>" data-rap-group-index="<%= group_index %>">

    <span>
      <%= t('ransack.advanced_search.condition_group.match') %>
      <%= frm.combinator_select({}, {class: 'form-control input-sm'}) %>
      <%= t('ransack.advanced_search.condition_group.match_condition') %>
      <%= render 'ransack_advanced_plus/remove_button' %>
    </span>

    <%= frm.condition_fields do |c| %>
        <%= render partial: 'ransack_advanced_plus/condition_fields', locals: {frm: c} %>
    <% end %>

    <a href="" data-rap-type="condition" class="ransack_advanced_plus_add_button">Condição</a>

    <%= frm.grouping_fields do |g| %>
        <%= render partial: 'ransack_advanced_plus/grouping_fields', locals: {frm: g} %>
    <% end %>

</div>

app/views/ransack_advanced_plus/_predicates.html.erb
<%= frm.predicate_select(@rap_operators, {class: 'ransack-predicate-select form-control input-sm'}) %>

app/views/ransack_advanced_plus/_remove_button.html.erb
<%= link_to '', nil, class: 'ransack_advanced_plus_remove_button' %>

app/views/ransack_advanced_plus/_saved_searches_list.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= t('ransack.saved_search.title') %></div>
  <ul class="list-group lista-buscas">
    <% if @saved_searches.present? %>
      <% @saved_searches.each do |saved_search| %>
        <li class="list-group-item">
          <%= link_to url_for(saved_search: saved_search.id), method: :post do %>
            <%= saved_search.description %>
          <% end %>
          <div class="pull-right ransack-saved-search-delete">
            <%= link_to saved_search_path(id: saved_search.id, redirect_to: redirect_path),
                { method: :delete, title: t('ransack.advanced_search.form.delete_saved_search'),
                  data: { confirm: t('ransack.advanced_search.form.delete_saved_search_confirm'),
                  toggle: 'tooltip', placement: 'bottom' } } do %>
              <i class="glyphicon glyphicon-trash text-danger"></i>
            <% end %>
          </div>
        </li>
      <% end %>
    <% else %>
      <li class="list-group-item">
        <em><%= t('ransack.saved_search.empty_list') %></em>
      </li>
    <% end %>
  </ul>
</div>

app/views/ransack_advanced_plus/_sort_fields.erb
<%= content_tag(:div,
  "#{button_to_remove_fields} #{f.sort_select({}, {class: 'form-control input-sm'})}",
  { class: 'fields', 'data-object-name' => f.object_name }, false) %>

app/views/ransack_advanced_plus/_sort_fields.html.erb
<%= content_tag(:div,
  "#{button_to_remove_fields} #{f.sort_select({}, {class: 'form-control input-sm'})}",
  { class: 'fields', 'data-object-name' => f.object_name }, false) %>

app/views/ransack_advanced_plus/_value_fields.erb
<%= content_tag(:span, frm.text_field(:value, {class: 'form-control input-sm ransack-attribute-value'}), { class: 'fields value', 'data-object-name' => frm.object_name }, false) %>

app/views/ransack_advanced_plus/_value_fields.html.erb
<% attribute_type = @attribute_type.present? ? @attribute_type.to_sym : nil %>
<% raise attribute_type.inspect %>
<% current_value = current_value.present? ? [current_value] : [] %>
<% form_class = 'form-control input-sm ransack-value-select' %>
<span class="fields value data-object-name <%= frm.object_name %>">
  <% frm_condition.object.inspect %>
  <% frm.object.value %>
  <% if attribute_type==:integer %>
    <%= frm.number_field(:value, {class: form_class}) %>
  <% elsif attribute_type==:float %>
  <% elsif attribute_type==:date %>
    <%= frm.date_field(:value, {class: form_class}) %>
  <% elsif attribute_type==:time %>
    <%= frm.time_field(:value, {class: form_class}) %>
  <% elsif attribute_type==:datetime %>
    <%= frm.datetime_field(:value, {class: form_class}) %>
  <% elsif attribute_type==:boolean %>
  <% elsif attribute_type==:collection %>
    <%= frm.select(:value, current_value, {include_blank: true}, {class: form_class}) %>
  <% else %>
      <%= frm.text_field(:value, {class: form_class}) %>
  <% end %>
</span>